### ISSUE TITLE
double with ParallelGenerator() as ...:

### ISSUE THREAD

**Issue by leehosu01** [wetneb/multiprocessing_generator#6]
Thanks for provide the simple multiprocessing generator
But I found one error with following code,
```
from multiprocessing_generator import ParallelGenerator
with ParallelGenerator(I for I in range(10)) as pg1:
    with ParallelGenerator(I for I in pg1) as pg2:
        for I in pg2:
            pass
```
the error was
```
Traceback (most recent call last):

  File "/home/.../Desktop/multiprocessing_generator/untitled1.py", line 27, in <module>
    for I in pg2:

  File "/home/.../.local/lib/python3.8/site-packages/multiprocessing_generator/__init__.py", line 74, in __next__
    return self.next()

  File "/home/.../.local/lib/python3.8/site-packages/multiprocessing_generator/__init__.py", line 98, in next
    raise item.exception

AssertionError: can only test a child process
```

It event if using ParallelGenerator multiple times .

**Comment by wetneb** [comment]
Interesting, I had not thought about this use case! If you can think of a solution, I would be curious to read it :)

**Comment by leehosu01** [comment]
finish debugging and make pull request
https://github.com/wetneb/multiprocessing_generator/pull/7

**Comment by wetneb** [comment]
Thank you very much! Let's keep this open until the PR is closed :)

**Comment by leehosu01** [comment]
sorry, not critical bug, but zombie process is created. 
I will fix and make PR later

**Comment by wetneb** [comment]
Thanks a lot!

**Comment by leehosu01** [comment]
I finish debugging and test.
the problem code:

```
with ParallelGenerator(I for I in range(10)) as pg1:
    with ParallelGenerator(I for I in pg1) as pg2:
        for I in pg2:
            pass
```

short:  gererator `pg1` make in main, but `pg1.next()` run in `pg2`.

detail:
`pg1` generator's process id as `p1`,
but `pg2` wrapper (id p2) try to get `next` from `orig_gen`.                    
`pg1`'s function `next` will run on `p2`

If generator finish with `StopIteration`, then call `self.process.is_alive()` ( = `p1.is_alive() `)
But `p1` is not child of `p2` 
So, it must make `AssertionError: can only test a child process`

Again, `p1`'s `self.process.is_alive()` is run on `p2`, not `main`


solution:
for simple coding, at last of `__init__.py`
```
except Exception:
    raise
```
is possible (will terminate late at `__exit__` )

__But__ for early termination, I make function `finish_if_possible()`

`self.process.terminate()` is not limit execute by parent process. But I think it will have some unknown counter example.
 So, in my implementation, only process with `ppid` allow try `terminate`.
